exports.props = {
	"gender": "/people/person/gender",
	"place_of_birth": "/people/person/place_of_birth",
	"images": "/common/topic/image",
	"nationality": "/people/person/nationality",
	"date_of_birth": "/people/person/date_of_birth",
	"date_of_death": "/people/deceased_person/date_of_death",
	"parents": "/people/person/parents",
	"children": "/people/person/children",
	"spouse": "/people/marriage/spouse",
	"degree": "/education/education/degree",
	"schools": "/education/education/institution",
	"profession": "/people/person/profession",
	"education": "/people/person/education",
	"website": "/common/topic/official_website",
	"social_presence": "/common/topic/social_media_presence",
	"geolocation": "/location/location/geolocation",
	"twitter": "twitter:key",
	"facebook": "facebook:key",
	"gplus": "gplus:key",
};